version: '3'
services:
  spark-driver:
    image: delta-spark:2.2.0
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - './:/mnt'
  spark-worker-1:
    image: delta-spark:2.2.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-driver:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: delta-spark:2.2.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-driver:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  #jupyter-notebook:
  #  image: dimajix/jupyter-spark:latest
  #  command: notebook
  #  build:
  #    context:  .
  #    args:
  #      http_proxy: ${http_proxy}
  #      https_proxy: ${https_proxy}
  #  env_file:
  #    - docker-compose.env
  #  environment:
  #    - http_proxy=${http_proxy}
  #    - https_proxy=${https_proxy}
  #  expose:
  #    - 8888
  #  ports:
  #    - 8888:8888
